version: 2

workflows:
  version: 2
  buid_and_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master


jobs:
  build_and_test:
    working_directory: ~/promise-minimum-time
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn --non-interactive
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn test --collectCoverage
      - run: yarn build
      - persist_to_workspace:
          root:  .
          paths:
            - node_modules
            - yarn.lock
            - dist

  deploy:
    working_directory: ~/promise-minimum-time
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: ~/promise-minimum-time

      - run: yarn semantic-release